import { describe, expect, it } from 'vitest'
import { vitePluginUseServer } from './plugin'

// The server-references manifest is generated by iterating serverReferenceMetaMap.
// That map is populated in module transform order, which is pass/discovery-order
// dependent, so without sorting the manifest's byte output varies build to build.
// The sibling maps (clientReferenceMetaMap, serverResourcesMetaMap) are sorted in
// stabilize(), but stabilize() runs after the rsc build has already emitted this
// manifest, so the manifest is sorted at emit time instead. This pins that order.

type Manager = Parameters<typeof vitePluginUseServer>[1]

function loadManifestHandler() {
  const manager = {
    config: { command: 'build' },
    serverReferenceMetaMap: {},
  } as unknown as Manager
  const plugins = vitePluginUseServer({}, manager)
  const plugin = plugins.find(
    (p) => p.name === 'rsc:virtual-vite-rsc/server-references',
  )
  const load = plugin?.load
  if (!load || typeof load === 'function' || !('handler' in load)) {
    throw new Error('expected an object load hook')
  }
  const handler = load.handler as (...args: any[]) => any
  async function manifestCode() {
    const ctx = { environment: { mode: 'build' } }
    const result = await handler.call(
      ctx,
      '\0virtual:vite-rsc/server-references',
      undefined,
    )
    return typeof result === 'string' ? result : result.code
  }
  return { manager, manifestCode }
}

describe('server-references manifest order', () => {
  it('build: entries are emitted sorted by reference key regardless of insertion order', async () => {
    const { manager, manifestCode } = loadManifestHandler()
    // Insertion order is deliberately unsorted (c, a, b).
    manager.serverReferenceMetaMap['/src/z.tsx'] = {
      importId: '/src/z.tsx',
      referenceKey: 'cccc0000',
      exportNames: ['zAction'],
    }
    manager.serverReferenceMetaMap['/src/y.tsx'] = {
      importId: '/src/y.tsx',
      referenceKey: 'aaaa1111',
      exportNames: ['yAction'],
    }
    manager.serverReferenceMetaMap['/src/x.tsx'] = {
      importId: '/src/x.tsx',
      referenceKey: 'bbbb2222',
      exportNames: ['xAction'],
    }

    const code = await manifestCode()

    const posA = code.indexOf('"aaaa1111"')
    const posB = code.indexOf('"bbbb2222"')
    const posC = code.indexOf('"cccc0000"')
    expect(posA).toBeGreaterThanOrEqual(0)
    expect(posB).toBeGreaterThanOrEqual(0)
    expect(posC).toBeGreaterThanOrEqual(0)
    // Emitted in sorted order (a < b < c), not insertion order (c, a, b).
    expect(posA).toBeLessThan(posB)
    expect(posB).toBeLessThan(posC)
  })
})
